Разбивает на презентеры
htmlacademy-ecmascript/1248355-cinemaddict-19 pull request #9
Opened 2022-12-29 08:04 UTC by AndreyOtin

2023-01-07 18:48 UTC, VishniakovaAlina requested changes

2023-01-07 18:48 UTC, VishniakovaAlina commented on src/presenters/films-list-presenter.js
> +    this.#renderFilms(0, Math.min(this.#films.length, FILMS_COUNT_PER_CLICK));
0 выноси в константу, не должно быть в проекте магически чисел

2023-01-07 18:48 UTC, VishniakovaAlina commented on src/presenters/films-presenter.js
> +  }
Возможно стоит разбить его на несколько презентеров что бы этот отвечал только за отрисовку фильмов

2023-01-07 18:48 UTC, VishniakovaAlina commented on src/views/film-card-view.js
> +  #watchListClickHandler = () => {
addToWatchListClickHandler - если это функция, то должно быть действие в названии, что именно она делает

2023-01-11 11:17 UTC, AndreyOtin commented on src/views/film-card-view.js
> +  #watchListClickHandler = () => {
Делал в соответсвии с Д4. Укажу название элемелемента перед click для ясности.

2023-01-11 12:13 UTC, merged